#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UELWeb2Hasako.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HaSakoProject")]
	public partial class dbHasakoProjectDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBLOG(BLOG instance);
    partial void UpdateBLOG(BLOG instance);
    partial void DeleteBLOG(BLOG instance);
    partial void InsertTHANHTOAN(THANHTOAN instance);
    partial void UpdateTHANHTOAN(THANHTOAN instance);
    partial void DeleteTHANHTOAN(THANHTOAN instance);
    partial void InsertCHITIETDONHANG(CHITIETDONHANG instance);
    partial void UpdateCHITIETDONHANG(CHITIETDONHANG instance);
    partial void DeleteCHITIETDONHANG(CHITIETDONHANG instance);
    partial void InsertCHITIETNHAPHANG(CHITIETNHAPHANG instance);
    partial void UpdateCHITIETNHAPHANG(CHITIETNHAPHANG instance);
    partial void DeleteCHITIETNHAPHANG(CHITIETNHAPHANG instance);
    partial void InsertCHITIETTHANHTOAN(CHITIETTHANHTOAN instance);
    partial void UpdateCHITIETTHANHTOAN(CHITIETTHANHTOAN instance);
    partial void DeleteCHITIETTHANHTOAN(CHITIETTHANHTOAN instance);
    partial void InsertDANHMUCHAISANKHO(DANHMUCHAISANKHO instance);
    partial void UpdateDANHMUCHAISANKHO(DANHMUCHAISANKHO instance);
    partial void DeleteDANHMUCHAISANKHO(DANHMUCHAISANKHO instance);
    partial void InsertDONHANG(DONHANG instance);
    partial void UpdateDONHANG(DONHANG instance);
    partial void DeleteDONHANG(DONHANG instance);
    partial void InsertHINHTHUCTHANHTOAN(HINHTHUCTHANHTOAN instance);
    partial void UpdateHINHTHUCTHANHTOAN(HINHTHUCTHANHTOAN instance);
    partial void DeleteHINHTHUCTHANHTOAN(HINHTHUCTHANHTOAN instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertMOTAHAISANKHO(MOTAHAISANKHO instance);
    partial void UpdateMOTAHAISANKHO(MOTAHAISANKHO instance);
    partial void DeleteMOTAHAISANKHO(MOTAHAISANKHO instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertTAIKHOANNHANVIEN(TAIKHOANNHANVIEN instance);
    partial void UpdateTAIKHOANNHANVIEN(TAIKHOANNHANVIEN instance);
    partial void DeleteTAIKHOANNHANVIEN(TAIKHOANNHANVIEN instance);
    partial void InsertHAISANKHO(HAISANKHO instance);
    partial void UpdateHAISANKHO(HAISANKHO instance);
    partial void DeleteHAISANKHO(HAISANKHO instance);
    #endregion
		
		public dbHasakoProjectDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HaSakoProjectConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbHasakoProjectDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbHasakoProjectDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbHasakoProjectDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbHasakoProjectDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BLOG> BLOGs
		{
			get
			{
				return this.GetTable<BLOG>();
			}
		}
		
		public System.Data.Linq.Table<THANHTOAN> THANHTOANs
		{
			get
			{
				return this.GetTable<THANHTOAN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this.GetTable<CHITIETDONHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETNHAPHANG> CHITIETNHAPHANGs
		{
			get
			{
				return this.GetTable<CHITIETNHAPHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETTHANHTOAN> CHITIETTHANHTOANs
		{
			get
			{
				return this.GetTable<CHITIETTHANHTOAN>();
			}
		}
		
		public System.Data.Linq.Table<DANHMUCHAISANKHO> DANHMUCHAISANKHOs
		{
			get
			{
				return this.GetTable<DANHMUCHAISANKHO>();
			}
		}
		
		public System.Data.Linq.Table<DONHANG> DONHANGs
		{
			get
			{
				return this.GetTable<DONHANG>();
			}
		}
		
		public System.Data.Linq.Table<HINHTHUCTHANHTOAN> HINHTHUCTHANHTOANs
		{
			get
			{
				return this.GetTable<HINHTHUCTHANHTOAN>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<MOTAHAISANKHO> MOTAHAISANKHOs
		{
			get
			{
				return this.GetTable<MOTAHAISANKHO>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOANNHANVIEN> TAIKHOANNHANVIENs
		{
			get
			{
				return this.GetTable<TAIKHOANNHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<HAISANKHO> HAISANKHOs
		{
			get
			{
				return this.GetTable<HAISANKHO>();
			}
		}
		
		public System.Data.Linq.Table<KHUYENMAI> KHUYENMAIs
		{
			get
			{
				return this.GetTable<KHUYENMAI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BLOG")]
	public partial class BLOG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBlog;
		
		private int _MaNV;
		
		private string _Tieude;
		
		private string _Noidung;
		
		private System.Data.Linq.Binary _Hinhanh;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		private System.DateTime _ngaychinhsua;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBlogChanging(int value);
    partial void OnMaBlogChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnTieudeChanging(string value);
    partial void OnTieudeChanged();
    partial void OnNoidungChanging(string value);
    partial void OnNoidungChanged();
    partial void OnHinhanhChanging(System.Data.Linq.Binary value);
    partial void OnHinhanhChanged();
    partial void OnNgaydangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangChanged();
    partial void OnngaychinhsuaChanging(System.DateTime value);
    partial void OnngaychinhsuaChanged();
    #endregion
		
		public BLOG()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBlog", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBlog
		{
			get
			{
				return this._MaBlog;
			}
			set
			{
				if ((this._MaBlog != value))
				{
					this.OnMaBlogChanging(value);
					this.SendPropertyChanging();
					this._MaBlog = value;
					this.SendPropertyChanged("MaBlog");
					this.OnMaBlogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieude", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Tieude
		{
			get
			{
				return this._Tieude;
			}
			set
			{
				if ((this._Tieude != value))
				{
					this.OnTieudeChanging(value);
					this.SendPropertyChanging();
					this._Tieude = value;
					this.SendPropertyChanged("Tieude");
					this.OnTieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this.OnNoidungChanging(value);
					this.SendPropertyChanging();
					this._Noidung = value;
					this.SendPropertyChanged("Noidung");
					this.OnNoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this.OnHinhanhChanging(value);
					this.SendPropertyChanging();
					this._Hinhanh = value;
					this.SendPropertyChanged("Hinhanh");
					this.OnHinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this.OnNgaydangChanging(value);
					this.SendPropertyChanging();
					this._Ngaydang = value;
					this.SendPropertyChanged("Ngaydang");
					this.OnNgaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaychinhsua", DbType="DateTime NOT NULL")]
		public System.DateTime ngaychinhsua
		{
			get
			{
				return this._ngaychinhsua;
			}
			set
			{
				if ((this._ngaychinhsua != value))
				{
					this.OnngaychinhsuaChanging(value);
					this.SendPropertyChanging();
					this._ngaychinhsua = value;
					this.SendPropertyChanged("ngaychinhsua");
					this.OnngaychinhsuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_BLOG", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.BLOGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.BLOGs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANHTOAN")]
	public partial class THANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTT;
		
		private int _MaHTTT;
		
		private int _MaKH;
		
		private System.Nullable<System.DateTime> _Ngaygiothanhtoan;
		
		private EntitySet<CHITIETTHANHTOAN> _CHITIETTHANHTOANs;
		
		private EntityRef<HINHTHUCTHANHTOAN> _HINHTHUCTHANHTOAN;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(int value);
    partial void OnMaTTChanged();
    partial void OnMaHTTTChanging(int value);
    partial void OnMaHTTTChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnNgaygiothanhtoanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaygiothanhtoanChanged();
    #endregion
		
		public THANHTOAN()
		{
			this._CHITIETTHANHTOANs = new EntitySet<CHITIETTHANHTOAN>(new Action<CHITIETTHANHTOAN>(this.attach_CHITIETTHANHTOANs), new Action<CHITIETTHANHTOAN>(this.detach_CHITIETTHANHTOANs));
			this._HINHTHUCTHANHTOAN = default(EntityRef<HINHTHUCTHANHTOAN>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHTTT", DbType="Int NOT NULL")]
		public int MaHTTT
		{
			get
			{
				return this._MaHTTT;
			}
			set
			{
				if ((this._MaHTTT != value))
				{
					if (this._HINHTHUCTHANHTOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHTTTChanging(value);
					this.SendPropertyChanging();
					this._MaHTTT = value;
					this.SendPropertyChanged("MaHTTT");
					this.OnMaHTTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaygiothanhtoan", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaygiothanhtoan
		{
			get
			{
				return this._Ngaygiothanhtoan;
			}
			set
			{
				if ((this._Ngaygiothanhtoan != value))
				{
					this.OnNgaygiothanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Ngaygiothanhtoan = value;
					this.SendPropertyChanged("Ngaygiothanhtoan");
					this.OnNgaygiothanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHTOAN_CHITIETTHANHTOAN", Storage="_CHITIETTHANHTOANs", ThisKey="MaTT", OtherKey="MaTT")]
		public EntitySet<CHITIETTHANHTOAN> CHITIETTHANHTOANs
		{
			get
			{
				return this._CHITIETTHANHTOANs;
			}
			set
			{
				this._CHITIETTHANHTOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HINHTHUCTHANHTOAN_THANHTOAN", Storage="_HINHTHUCTHANHTOAN", ThisKey="MaHTTT", OtherKey="MaHTTT", IsForeignKey=true)]
		public HINHTHUCTHANHTOAN HINHTHUCTHANHTOAN
		{
			get
			{
				return this._HINHTHUCTHANHTOAN.Entity;
			}
			set
			{
				HINHTHUCTHANHTOAN previousValue = this._HINHTHUCTHANHTOAN.Entity;
				if (((previousValue != value) 
							|| (this._HINHTHUCTHANHTOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HINHTHUCTHANHTOAN.Entity = null;
						previousValue.THANHTOANs.Remove(this);
					}
					this._HINHTHUCTHANHTOAN.Entity = value;
					if ((value != null))
					{
						value.THANHTOANs.Add(this);
						this._MaHTTT = value.MaHTTT;
					}
					else
					{
						this._MaHTTT = default(int);
					}
					this.SendPropertyChanged("HINHTHUCTHANHTOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_THANHTOAN", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.THANHTOANs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.THANHTOANs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETTHANHTOANs(CHITIETTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.THANHTOAN = this;
		}
		
		private void detach_CHITIETTHANHTOANs(CHITIETTHANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.THANHTOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDONHANG")]
	public partial class CHITIETDONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDH;
		
		private int _MaHS;
		
		private int _Soluong;
		
		private int _Dongia;
		
		private System.Nullable<int> _TonggiaCTDH;
		
		private EntityRef<DONHANG> _DONHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDHChanging(int value);
    partial void OnMaDHChanged();
    partial void OnMaHSChanging(int value);
    partial void OnMaHSChanged();
    partial void OnSoluongChanging(int value);
    partial void OnSoluongChanged();
    partial void OnDongiaChanging(int value);
    partial void OnDongiaChanged();
    partial void OnTonggiaCTDHChanging(System.Nullable<int> value);
    partial void OnTonggiaCTDHChanged();
    #endregion
		
		public CHITIETDONHANG()
		{
			this._DONHANG = default(EntityRef<DONHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					if (this._DONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="Int NOT NULL")]
		public int MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this.OnMaHSChanging(value);
					this.SendPropertyChanging();
					this._MaHS = value;
					this.SendPropertyChanged("MaHS");
					this.OnMaHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int NOT NULL")]
		public int Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Int NOT NULL")]
		public int Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonggiaCTDH", DbType="Int")]
		public System.Nullable<int> TonggiaCTDH
		{
			get
			{
				return this._TonggiaCTDH;
			}
			set
			{
				if ((this._TonggiaCTDH != value))
				{
					this.OnTonggiaCTDHChanging(value);
					this.SendPropertyChanging();
					this._TonggiaCTDH = value;
					this.SendPropertyChanged("TonggiaCTDH");
					this.OnTonggiaCTDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_CHITIETDONHANG", Storage="_DONHANG", ThisKey="MaDH", OtherKey="MaDH", IsForeignKey=true)]
		public DONHANG DONHANG
		{
			get
			{
				return this._DONHANG.Entity;
			}
			set
			{
				DONHANG previousValue = this._DONHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONHANG.Entity = null;
						previousValue.CHITIETDONHANG = null;
					}
					this._DONHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANG = this;
						this._MaDH = value.MaDH;
					}
					else
					{
						this._MaDH = default(int);
					}
					this.SendPropertyChanged("DONHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETNHAPHANG")]
	public partial class CHITIETNHAPHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNH;
		
		private System.Nullable<System.DateTime> _Nhaynhapkho;
		
		private System.Nullable<int> _Soluongnhap;
		
		private EntitySet<HAISANKHO> _HAISANKHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNHChanging(int value);
    partial void OnMaNHChanged();
    partial void OnNhaynhapkhoChanging(System.Nullable<System.DateTime> value);
    partial void OnNhaynhapkhoChanged();
    partial void OnSoluongnhapChanging(System.Nullable<int> value);
    partial void OnSoluongnhapChanged();
    #endregion
		
		public CHITIETNHAPHANG()
		{
			this._HAISANKHOs = new EntitySet<HAISANKHO>(new Action<HAISANKHO>(this.attach_HAISANKHOs), new Action<HAISANKHO>(this.detach_HAISANKHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNH
		{
			get
			{
				return this._MaNH;
			}
			set
			{
				if ((this._MaNH != value))
				{
					this.OnMaNHChanging(value);
					this.SendPropertyChanging();
					this._MaNH = value;
					this.SendPropertyChanged("MaNH");
					this.OnMaNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhaynhapkho", DbType="DateTime")]
		public System.Nullable<System.DateTime> Nhaynhapkho
		{
			get
			{
				return this._Nhaynhapkho;
			}
			set
			{
				if ((this._Nhaynhapkho != value))
				{
					this.OnNhaynhapkhoChanging(value);
					this.SendPropertyChanging();
					this._Nhaynhapkho = value;
					this.SendPropertyChanged("Nhaynhapkho");
					this.OnNhaynhapkhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongnhap", DbType="Int")]
		public System.Nullable<int> Soluongnhap
		{
			get
			{
				return this._Soluongnhap;
			}
			set
			{
				if ((this._Soluongnhap != value))
				{
					this.OnSoluongnhapChanging(value);
					this.SendPropertyChanging();
					this._Soluongnhap = value;
					this.SendPropertyChanged("Soluongnhap");
					this.OnSoluongnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHITIETNHAPHANG_HAISANKHO", Storage="_HAISANKHOs", ThisKey="MaNH", OtherKey="MaNH")]
		public EntitySet<HAISANKHO> HAISANKHOs
		{
			get
			{
				return this._HAISANKHOs;
			}
			set
			{
				this._HAISANKHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HAISANKHOs(HAISANKHO entity)
		{
			this.SendPropertyChanging();
			entity.CHITIETNHAPHANG = this;
		}
		
		private void detach_HAISANKHOs(HAISANKHO entity)
		{
			this.SendPropertyChanging();
			entity.CHITIETNHAPHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETTHANHTOAN")]
	public partial class CHITIETTHANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCTTT;
		
		private int _MaDH;
		
		private int _MaTT;
		
		private System.Nullable<int> _Giamgia;
		
		private int _Tongtienthanhtoan;
		
		private EntityRef<THANHTOAN> _THANHTOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTTTChanging(int value);
    partial void OnMaCTTTChanged();
    partial void OnMaDHChanging(int value);
    partial void OnMaDHChanged();
    partial void OnMaTTChanging(int value);
    partial void OnMaTTChanged();
    partial void OnGiamgiaChanging(System.Nullable<int> value);
    partial void OnGiamgiaChanged();
    partial void OnTongtienthanhtoanChanging(int value);
    partial void OnTongtienthanhtoanChanged();
    #endregion
		
		public CHITIETTHANHTOAN()
		{
			this._THANHTOAN = default(EntityRef<THANHTOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTTT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCTTT
		{
			get
			{
				return this._MaCTTT;
			}
			set
			{
				if ((this._MaCTTT != value))
				{
					this.OnMaCTTTChanging(value);
					this.SendPropertyChanging();
					this._MaCTTT = value;
					this.SendPropertyChanged("MaCTTT");
					this.OnMaCTTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", DbType="Int NOT NULL")]
		public int MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Int NOT NULL")]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					if (this._THANHTOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giamgia", DbType="Int")]
		public System.Nullable<int> Giamgia
		{
			get
			{
				return this._Giamgia;
			}
			set
			{
				if ((this._Giamgia != value))
				{
					this.OnGiamgiaChanging(value);
					this.SendPropertyChanging();
					this._Giamgia = value;
					this.SendPropertyChanged("Giamgia");
					this.OnGiamgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tongtienthanhtoan", DbType="Int NOT NULL")]
		public int Tongtienthanhtoan
		{
			get
			{
				return this._Tongtienthanhtoan;
			}
			set
			{
				if ((this._Tongtienthanhtoan != value))
				{
					this.OnTongtienthanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Tongtienthanhtoan = value;
					this.SendPropertyChanged("Tongtienthanhtoan");
					this.OnTongtienthanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHTOAN_CHITIETTHANHTOAN", Storage="_THANHTOAN", ThisKey="MaTT", OtherKey="MaTT", IsForeignKey=true)]
		public THANHTOAN THANHTOAN
		{
			get
			{
				return this._THANHTOAN.Entity;
			}
			set
			{
				THANHTOAN previousValue = this._THANHTOAN.Entity;
				if (((previousValue != value) 
							|| (this._THANHTOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANHTOAN.Entity = null;
						previousValue.CHITIETTHANHTOANs.Remove(this);
					}
					this._THANHTOAN.Entity = value;
					if ((value != null))
					{
						value.CHITIETTHANHTOANs.Add(this);
						this._MaTT = value.MaTT;
					}
					else
					{
						this._MaTT = default(int);
					}
					this.SendPropertyChanged("THANHTOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHMUCHAISANKHO")]
	public partial class DANHMUCHAISANKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDM;
		
		private string _TenDM;
		
		private EntitySet<HAISANKHO> _HAISANKHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDMChanging(int value);
    partial void OnMaDMChanged();
    partial void OnTenDMChanging(string value);
    partial void OnTenDMChanged();
    #endregion
		
		public DANHMUCHAISANKHO()
		{
			this._HAISANKHOs = new EntitySet<HAISANKHO>(new Action<HAISANKHO>(this.attach_HAISANKHOs), new Action<HAISANKHO>(this.detach_HAISANKHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDM
		{
			get
			{
				return this._MaDM;
			}
			set
			{
				if ((this._MaDM != value))
				{
					this.OnMaDMChanging(value);
					this.SendPropertyChanging();
					this._MaDM = value;
					this.SendPropertyChanged("MaDM");
					this.OnMaDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDM", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string TenDM
		{
			get
			{
				return this._TenDM;
			}
			set
			{
				if ((this._TenDM != value))
				{
					this.OnTenDMChanging(value);
					this.SendPropertyChanging();
					this._TenDM = value;
					this.SendPropertyChanged("TenDM");
					this.OnTenDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUCHAISANKHO_HAISANKHO", Storage="_HAISANKHOs", ThisKey="MaDM", OtherKey="MaDM")]
		public EntitySet<HAISANKHO> HAISANKHOs
		{
			get
			{
				return this._HAISANKHOs;
			}
			set
			{
				this._HAISANKHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HAISANKHOs(HAISANKHO entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCHAISANKHO = this;
		}
		
		private void detach_HAISANKHOs(HAISANKHO entity)
		{
			this.SendPropertyChanging();
			entity.DANHMUCHAISANKHO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONHANG")]
	public partial class DONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDH;
		
		private int _MaKH;
		
		private int _MaNV;
		
		private bool _Dathanhtoan;
		
		private System.DateTime _Ngaydathang;
		
		private System.DateTime _Ngaygiaohang;
		
		private string _Diachigiaohang;
		
		private System.Nullable<bool> _Tinhtranggiaohang;
		
		private int _Thanhtien;
		
		private EntityRef<CHITIETDONHANG> _CHITIETDONHANG;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDHChanging(int value);
    partial void OnMaDHChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnDathanhtoanChanging(bool value);
    partial void OnDathanhtoanChanged();
    partial void OnNgaydathangChanging(System.DateTime value);
    partial void OnNgaydathangChanged();
    partial void OnNgaygiaohangChanging(System.DateTime value);
    partial void OnNgaygiaohangChanged();
    partial void OnDiachigiaohangChanging(string value);
    partial void OnDiachigiaohangChanged();
    partial void OnTinhtranggiaohangChanging(System.Nullable<bool> value);
    partial void OnTinhtranggiaohangChanged();
    partial void OnThanhtienChanging(int value);
    partial void OnThanhtienChanged();
    #endregion
		
		public DONHANG()
		{
			this._CHITIETDONHANG = default(EntityRef<CHITIETDONHANG>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dathanhtoan", DbType="Bit NOT NULL")]
		public bool Dathanhtoan
		{
			get
			{
				return this._Dathanhtoan;
			}
			set
			{
				if ((this._Dathanhtoan != value))
				{
					this.OnDathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Dathanhtoan = value;
					this.SendPropertyChanged("Dathanhtoan");
					this.OnDathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydathang", DbType="DateTime NOT NULL")]
		public System.DateTime Ngaydathang
		{
			get
			{
				return this._Ngaydathang;
			}
			set
			{
				if ((this._Ngaydathang != value))
				{
					this.OnNgaydathangChanging(value);
					this.SendPropertyChanging();
					this._Ngaydathang = value;
					this.SendPropertyChanged("Ngaydathang");
					this.OnNgaydathangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaygiaohang", DbType="DateTime NOT NULL")]
		public System.DateTime Ngaygiaohang
		{
			get
			{
				return this._Ngaygiaohang;
			}
			set
			{
				if ((this._Ngaygiaohang != value))
				{
					this.OnNgaygiaohangChanging(value);
					this.SendPropertyChanging();
					this._Ngaygiaohang = value;
					this.SendPropertyChanged("Ngaygiaohang");
					this.OnNgaygiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachigiaohang", DbType="NVarChar(128)")]
		public string Diachigiaohang
		{
			get
			{
				return this._Diachigiaohang;
			}
			set
			{
				if ((this._Diachigiaohang != value))
				{
					this.OnDiachigiaohangChanging(value);
					this.SendPropertyChanging();
					this._Diachigiaohang = value;
					this.SendPropertyChanged("Diachigiaohang");
					this.OnDiachigiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtranggiaohang", DbType="Bit")]
		public System.Nullable<bool> Tinhtranggiaohang
		{
			get
			{
				return this._Tinhtranggiaohang;
			}
			set
			{
				if ((this._Tinhtranggiaohang != value))
				{
					this.OnTinhtranggiaohangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtranggiaohang = value;
					this.SendPropertyChanged("Tinhtranggiaohang");
					this.OnTinhtranggiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhtien", DbType="Int NOT NULL")]
		public int Thanhtien
		{
			get
			{
				return this._Thanhtien;
			}
			set
			{
				if ((this._Thanhtien != value))
				{
					this.OnThanhtienChanging(value);
					this.SendPropertyChanging();
					this._Thanhtien = value;
					this.SendPropertyChanged("Thanhtien");
					this.OnThanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_CHITIETDONHANG", Storage="_CHITIETDONHANG", ThisKey="MaDH", OtherKey="MaDH", IsUnique=true, IsForeignKey=false)]
		public CHITIETDONHANG CHITIETDONHANG
		{
			get
			{
				return this._CHITIETDONHANG.Entity;
			}
			set
			{
				CHITIETDONHANG previousValue = this._CHITIETDONHANG.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETDONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETDONHANG.Entity = null;
						previousValue.DONHANG = null;
					}
					this._CHITIETDONHANG.Entity = value;
					if ((value != null))
					{
						value.DONHANG = this;
					}
					this.SendPropertyChanged("CHITIETDONHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONHANG", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DONHANGs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DONHANGs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_DONHANG", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.DONHANGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.DONHANGs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HINHTHUCTHANHTOAN")]
	public partial class HINHTHUCTHANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHTTT;
		
		private string _TenHTTT;
		
		private EntitySet<THANHTOAN> _THANHTOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHTTTChanging(int value);
    partial void OnMaHTTTChanged();
    partial void OnTenHTTTChanging(string value);
    partial void OnTenHTTTChanged();
    #endregion
		
		public HINHTHUCTHANHTOAN()
		{
			this._THANHTOANs = new EntitySet<THANHTOAN>(new Action<THANHTOAN>(this.attach_THANHTOANs), new Action<THANHTOAN>(this.detach_THANHTOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHTTT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHTTT
		{
			get
			{
				return this._MaHTTT;
			}
			set
			{
				if ((this._MaHTTT != value))
				{
					this.OnMaHTTTChanging(value);
					this.SendPropertyChanging();
					this._MaHTTT = value;
					this.SendPropertyChanged("MaHTTT");
					this.OnMaHTTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHTTT", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string TenHTTT
		{
			get
			{
				return this._TenHTTT;
			}
			set
			{
				if ((this._TenHTTT != value))
				{
					this.OnTenHTTTChanging(value);
					this.SendPropertyChanging();
					this._TenHTTT = value;
					this.SendPropertyChanged("TenHTTT");
					this.OnTenHTTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HINHTHUCTHANHTOAN_THANHTOAN", Storage="_THANHTOANs", ThisKey="MaHTTT", OtherKey="MaHTTT")]
		public EntitySet<THANHTOAN> THANHTOANs
		{
			get
			{
				return this._THANHTOANs;
			}
			set
			{
				this._THANHTOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THANHTOANs(THANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.HINHTHUCTHANHTOAN = this;
		}
		
		private void detach_THANHTOANs(THANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.HINHTHUCTHANHTOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TenKh;
		
		private string _Sodienthoai;
		
		private string _Email;
		
		private string _DiaChi;
		
		private System.Nullable<int> _Gioitinh;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private EntitySet<THANHTOAN> _THANHTOANs;
		
		private EntitySet<DONHANG> _DONHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTenKhChanging(string value);
    partial void OnTenKhChanged();
    partial void OnSodienthoaiChanging(string value);
    partial void OnSodienthoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGioitinhChanging(System.Nullable<int> value);
    partial void OnGioitinhChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._THANHTOANs = new EntitySet<THANHTOAN>(new Action<THANHTOAN>(this.attach_THANHTOANs), new Action<THANHTOAN>(this.detach_THANHTOANs));
			this._DONHANGs = new EntitySet<DONHANG>(new Action<DONHANG>(this.attach_DONHANGs), new Action<DONHANG>(this.detach_DONHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKh", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TenKh
		{
			get
			{
				return this._TenKh;
			}
			set
			{
				if ((this._TenKh != value))
				{
					this.OnTenKhChanging(value);
					this.SendPropertyChanging();
					this._TenKh = value;
					this.SendPropertyChanged("TenKh");
					this.OnTenKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodienthoai", DbType="NVarChar(128)")]
		public string Sodienthoai
		{
			get
			{
				return this._Sodienthoai;
			}
			set
			{
				if ((this._Sodienthoai != value))
				{
					this.OnSodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._Sodienthoai = value;
					this.SendPropertyChanged("Sodienthoai");
					this.OnSodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(128)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(64)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Int")]
		public System.Nullable<int> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_THANHTOAN", Storage="_THANHTOANs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<THANHTOAN> THANHTOANs
		{
			get
			{
				return this._THANHTOANs;
			}
			set
			{
				this._THANHTOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONHANG", Storage="_DONHANGs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DONHANG> DONHANGs
		{
			get
			{
				return this._DONHANGs;
			}
			set
			{
				this._DONHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THANHTOANs(THANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_THANHTOANs(THANHTOAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MOTAHAISANKHO")]
	public partial class MOTAHAISANKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHS;
		
		private string _Hinh1;
		
		private string _Hinh2;
		
		private string _Hinh3;
		
		private EntityRef<HAISANKHO> _HAISANKHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHSChanging(int value);
    partial void OnMaHSChanged();
    partial void OnHinh1Changing(string value);
    partial void OnHinh1Changed();
    partial void OnHinh2Changing(string value);
    partial void OnHinh2Changed();
    partial void OnHinh3Changing(string value);
    partial void OnHinh3Changed();
    #endregion
		
		public MOTAHAISANKHO()
		{
			this._HAISANKHO = default(EntityRef<HAISANKHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					if (this._HAISANKHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHSChanging(value);
					this.SendPropertyChanging();
					this._MaHS = value;
					this.SendPropertyChanged("MaHS");
					this.OnMaHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh1", DbType="NVarChar(MAX)")]
		public string Hinh1
		{
			get
			{
				return this._Hinh1;
			}
			set
			{
				if ((this._Hinh1 != value))
				{
					this.OnHinh1Changing(value);
					this.SendPropertyChanging();
					this._Hinh1 = value;
					this.SendPropertyChanged("Hinh1");
					this.OnHinh1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh2", DbType="NVarChar(MAX)")]
		public string Hinh2
		{
			get
			{
				return this._Hinh2;
			}
			set
			{
				if ((this._Hinh2 != value))
				{
					this.OnHinh2Changing(value);
					this.SendPropertyChanging();
					this._Hinh2 = value;
					this.SendPropertyChanged("Hinh2");
					this.OnHinh2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh3", DbType="NVarChar(MAX)")]
		public string Hinh3
		{
			get
			{
				return this._Hinh3;
			}
			set
			{
				if ((this._Hinh3 != value))
				{
					this.OnHinh3Changing(value);
					this.SendPropertyChanging();
					this._Hinh3 = value;
					this.SendPropertyChanged("Hinh3");
					this.OnHinh3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HAISANKHO_MOTAHAISANKHO", Storage="_HAISANKHO", ThisKey="MaHS", OtherKey="MaHS", IsForeignKey=true)]
		public HAISANKHO HAISANKHO
		{
			get
			{
				return this._HAISANKHO.Entity;
			}
			set
			{
				HAISANKHO previousValue = this._HAISANKHO.Entity;
				if (((previousValue != value) 
							|| (this._HAISANKHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HAISANKHO.Entity = null;
						previousValue.MOTAHAISANKHO = null;
					}
					this._HAISANKHO.Entity = value;
					if ((value != null))
					{
						value.MOTAHAISANKHO = this;
						this._MaHS = value.MaHS;
					}
					else
					{
						this._MaHS = default(int);
					}
					this.SendPropertyChanged("HAISANKHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _TenNV;
		
		private string _Sodienthoai;
		
		private string _Email;
		
		private string _Diachi;
		
		private System.Nullable<int> _Gioitinh;
		
		private EntitySet<BLOG> _BLOGs;
		
		private EntitySet<DONHANG> _DONHANGs;
		
		private EntityRef<TAIKHOANNHANVIEN> _TAIKHOANNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnSodienthoaiChanging(string value);
    partial void OnSodienthoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnGioitinhChanging(System.Nullable<int> value);
    partial void OnGioitinhChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._BLOGs = new EntitySet<BLOG>(new Action<BLOG>(this.attach_BLOGs), new Action<BLOG>(this.detach_BLOGs));
			this._DONHANGs = new EntitySet<DONHANG>(new Action<DONHANG>(this.attach_DONHANGs), new Action<DONHANG>(this.detach_DONHANGs));
			this._TAIKHOANNHANVIEN = default(EntityRef<TAIKHOANNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodienthoai", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Sodienthoai
		{
			get
			{
				return this._Sodienthoai;
			}
			set
			{
				if ((this._Sodienthoai != value))
				{
					this.OnSodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._Sodienthoai = value;
					this.SendPropertyChanged("Sodienthoai");
					this.OnSodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(64)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(64)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Int")]
		public System.Nullable<int> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_BLOG", Storage="_BLOGs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<BLOG> BLOGs
		{
			get
			{
				return this._BLOGs;
			}
			set
			{
				this._BLOGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_DONHANG", Storage="_DONHANGs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<DONHANG> DONHANGs
		{
			get
			{
				return this._DONHANGs;
			}
			set
			{
				this._DONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOANNHANVIEN", Storage="_TAIKHOANNHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsUnique=true, IsForeignKey=false)]
		public TAIKHOANNHANVIEN TAIKHOANNHANVIEN
		{
			get
			{
				return this._TAIKHOANNHANVIEN.Entity;
			}
			set
			{
				TAIKHOANNHANVIEN previousValue = this._TAIKHOANNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOANNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOANNHANVIEN.Entity = null;
						previousValue.NHANVIEN = null;
					}
					this._TAIKHOANNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.NHANVIEN = this;
					}
					this.SendPropertyChanged("TAIKHOANNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BLOGs(BLOG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_BLOGs(BLOG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_DONHANGs(DONHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOANNHANVIEN")]
	public partial class TAIKHOANNHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private string _Phanquyen;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnPhanquyenChanging(string value);
    partial void OnPhanquyenChanged();
    #endregion
		
		public TAIKHOANNHANVIEN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phanquyen", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Phanquyen
		{
			get
			{
				return this._Phanquyen;
			}
			set
			{
				if ((this._Phanquyen != value))
				{
					this.OnPhanquyenChanging(value);
					this.SendPropertyChanging();
					this._Phanquyen = value;
					this.SendPropertyChanged("Phanquyen");
					this.OnPhanquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOANNHANVIEN", Storage="_NHANVIEN", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TAIKHOANNHANVIEN = null;
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANNHANVIEN = this;
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HAISANKHO")]
	public partial class HAISANKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHS;
		
		private string _TenHS;
		
		private int _Dongia;
		
		private string _Mota;
		
		private string _Anhbia;
		
		private System.Nullable<System.DateTime> _Ngaycapnhat;
		
		private string _Donvi;
		
		private System.Nullable<int> _Soluongton;
		
		private System.Nullable<int> _MaDM;
		
		private System.Nullable<int> _MaNH;
		
		private EntityRef<MOTAHAISANKHO> _MOTAHAISANKHO;
		
		private EntityRef<CHITIETNHAPHANG> _CHITIETNHAPHANG;
		
		private EntityRef<DANHMUCHAISANKHO> _DANHMUCHAISANKHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHSChanging(int value);
    partial void OnMaHSChanged();
    partial void OnTenHSChanging(string value);
    partial void OnTenHSChanged();
    partial void OnDongiaChanging(int value);
    partial void OnDongiaChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnAnhbiaChanging(string value);
    partial void OnAnhbiaChanged();
    partial void OnNgaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaycapnhatChanged();
    partial void OnDonviChanging(string value);
    partial void OnDonviChanged();
    partial void OnSoluongtonChanging(System.Nullable<int> value);
    partial void OnSoluongtonChanged();
    partial void OnMaDMChanging(System.Nullable<int> value);
    partial void OnMaDMChanged();
    partial void OnMaNHChanging(System.Nullable<int> value);
    partial void OnMaNHChanged();
    #endregion
		
		public HAISANKHO()
		{
			this._MOTAHAISANKHO = default(EntityRef<MOTAHAISANKHO>);
			this._CHITIETNHAPHANG = default(EntityRef<CHITIETNHAPHANG>);
			this._DANHMUCHAISANKHO = default(EntityRef<DANHMUCHAISANKHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this.OnMaHSChanging(value);
					this.SendPropertyChanging();
					this._MaHS = value;
					this.SendPropertyChanged("MaHS");
					this.OnMaHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHS", DbType="NVarChar(128)")]
		public string TenHS
		{
			get
			{
				return this._TenHS;
			}
			set
			{
				if ((this._TenHS != value))
				{
					this.OnTenHSChanging(value);
					this.SendPropertyChanging();
					this._TenHS = value;
					this.SendPropertyChanged("TenHS");
					this.OnTenHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Int NOT NULL")]
		public int Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anhbia", DbType="NVarChar(MAX)")]
		public string Anhbia
		{
			get
			{
				return this._Anhbia;
			}
			set
			{
				if ((this._Anhbia != value))
				{
					this.OnAnhbiaChanging(value);
					this.SendPropertyChanging();
					this._Anhbia = value;
					this.SendPropertyChanged("Anhbia");
					this.OnAnhbiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaycapnhat
		{
			get
			{
				return this._Ngaycapnhat;
			}
			set
			{
				if ((this._Ngaycapnhat != value))
				{
					this.OnNgaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._Ngaycapnhat = value;
					this.SendPropertyChanged("Ngaycapnhat");
					this.OnNgaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvi", DbType="NVarChar(20)")]
		public string Donvi
		{
			get
			{
				return this._Donvi;
			}
			set
			{
				if ((this._Donvi != value))
				{
					this.OnDonviChanging(value);
					this.SendPropertyChanging();
					this._Donvi = value;
					this.SendPropertyChanged("Donvi");
					this.OnDonviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongton", DbType="Int")]
		public System.Nullable<int> Soluongton
		{
			get
			{
				return this._Soluongton;
			}
			set
			{
				if ((this._Soluongton != value))
				{
					this.OnSoluongtonChanging(value);
					this.SendPropertyChanging();
					this._Soluongton = value;
					this.SendPropertyChanged("Soluongton");
					this.OnSoluongtonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDM", DbType="Int")]
		public System.Nullable<int> MaDM
		{
			get
			{
				return this._MaDM;
			}
			set
			{
				if ((this._MaDM != value))
				{
					if (this._DANHMUCHAISANKHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDMChanging(value);
					this.SendPropertyChanging();
					this._MaDM = value;
					this.SendPropertyChanged("MaDM");
					this.OnMaDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNH", DbType="Int")]
		public System.Nullable<int> MaNH
		{
			get
			{
				return this._MaNH;
			}
			set
			{
				if ((this._MaNH != value))
				{
					if (this._CHITIETNHAPHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNHChanging(value);
					this.SendPropertyChanging();
					this._MaNH = value;
					this.SendPropertyChanged("MaNH");
					this.OnMaNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HAISANKHO_MOTAHAISANKHO", Storage="_MOTAHAISANKHO", ThisKey="MaHS", OtherKey="MaHS", IsUnique=true, IsForeignKey=false)]
		public MOTAHAISANKHO MOTAHAISANKHO
		{
			get
			{
				return this._MOTAHAISANKHO.Entity;
			}
			set
			{
				MOTAHAISANKHO previousValue = this._MOTAHAISANKHO.Entity;
				if (((previousValue != value) 
							|| (this._MOTAHAISANKHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MOTAHAISANKHO.Entity = null;
						previousValue.HAISANKHO = null;
					}
					this._MOTAHAISANKHO.Entity = value;
					if ((value != null))
					{
						value.HAISANKHO = this;
					}
					this.SendPropertyChanged("MOTAHAISANKHO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHITIETNHAPHANG_HAISANKHO", Storage="_CHITIETNHAPHANG", ThisKey="MaNH", OtherKey="MaNH", IsForeignKey=true)]
		public CHITIETNHAPHANG CHITIETNHAPHANG
		{
			get
			{
				return this._CHITIETNHAPHANG.Entity;
			}
			set
			{
				CHITIETNHAPHANG previousValue = this._CHITIETNHAPHANG.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETNHAPHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETNHAPHANG.Entity = null;
						previousValue.HAISANKHOs.Remove(this);
					}
					this._CHITIETNHAPHANG.Entity = value;
					if ((value != null))
					{
						value.HAISANKHOs.Add(this);
						this._MaNH = value.MaNH;
					}
					else
					{
						this._MaNH = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHITIETNHAPHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANHMUCHAISANKHO_HAISANKHO", Storage="_DANHMUCHAISANKHO", ThisKey="MaDM", OtherKey="MaDM", IsForeignKey=true)]
		public DANHMUCHAISANKHO DANHMUCHAISANKHO
		{
			get
			{
				return this._DANHMUCHAISANKHO.Entity;
			}
			set
			{
				DANHMUCHAISANKHO previousValue = this._DANHMUCHAISANKHO.Entity;
				if (((previousValue != value) 
							|| (this._DANHMUCHAISANKHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANHMUCHAISANKHO.Entity = null;
						previousValue.HAISANKHOs.Remove(this);
					}
					this._DANHMUCHAISANKHO.Entity = value;
					if ((value != null))
					{
						value.HAISANKHOs.Add(this);
						this._MaDM = value.MaDM;
					}
					else
					{
						this._MaDM = default(Nullable<int>);
					}
					this.SendPropertyChanged("DANHMUCHAISANKHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHUYENMAI")]
	public partial class KHUYENMAI
	{
		
		private int _MaHS;
		
		private int _PhanTramGiam;
		
		private bool _TinhTrangKM;
		
		public KHUYENMAI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHS", DbType="Int NOT NULL")]
		public int MaHS
		{
			get
			{
				return this._MaHS;
			}
			set
			{
				if ((this._MaHS != value))
				{
					this._MaHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanTramGiam", DbType="Int NOT NULL")]
		public int PhanTramGiam
		{
			get
			{
				return this._PhanTramGiam;
			}
			set
			{
				if ((this._PhanTramGiam != value))
				{
					this._PhanTramGiam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangKM", DbType="Bit NOT NULL")]
		public bool TinhTrangKM
		{
			get
			{
				return this._TinhTrangKM;
			}
			set
			{
				if ((this._TinhTrangKM != value))
				{
					this._TinhTrangKM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
